"""empty message

Revision ID: 44c4966407cb
Revises: 
Create Date: 2021-07-24 14:20:05.249731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c4966407cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descr', sa.String(length=150), nullable=False),
    sa.Column('card', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('usrv', sa.String(length=150), nullable=True),
    sa.Column('fr_om', sa.String(length=150), nullable=True),
    sa.Column('inp_ut', sa.String(length=150), nullable=True),
    sa.Column('avail_balance', sa.String(length=150), nullable=False),
    sa.Column('curr_balance', sa.String(length=150), nullable=False),
    sa.Column('cedis', sa.String(length=150), nullable=True),
    sa.Column('pesewas', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sent_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descr', sa.String(length=150), nullable=False),
    sa.Column('card', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('requisit', sa.String(length=150), nullable=True),
    sa.Column('t_o', sa.String(length=150), nullable=True),
    sa.Column('out_put', sa.String(length=150), nullable=True),
    sa.Column('avail_balance', sa.String(length=150), nullable=False),
    sa.Column('curr_balance', sa.String(length=150), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_items')
    op.drop_table('items')
    # ### end Alembic commands ###
