"""empty message

Revision ID: 776bff268277
Revises: e9c27e2098da
Create Date: 2021-07-21 20:21:31.656211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776bff268277'
down_revision = 'e9c27e2098da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descr', sa.String(length=150), nullable=False),
    sa.Column('card', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('requisit', sa.String(length=150), nullable=True),
    sa.Column('t_o', sa.String(length=150), nullable=True),
    sa.Column('out_put', sa.String(length=150), nullable=True),
    sa.Column('balance', sa.String(length=150), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_items')
    # ### end Alembic commands ###
