"""empty message

Revision ID: afe6f50e26b5
Revises: 
Create Date: 2021-07-30 07:35:48.737138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe6f50e26b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_trans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descr', sa.String(length=150), nullable=True),
    sa.Column('card', sa.String(length=150), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('usrv', sa.String(length=150), nullable=True),
    sa.Column('requisit', sa.String(length=150), nullable=True),
    sa.Column('fr_om', sa.String(length=150), nullable=True),
    sa.Column('t_o', sa.String(length=150), nullable=True),
    sa.Column('inp_ut', sa.String(length=150), nullable=True),
    sa.Column('out_put', sa.String(length=150), nullable=True),
    sa.Column('curr_balance', sa.String(length=150), nullable=True),
    sa.Column('cedis', sa.String(length=150), nullable=True),
    sa.Column('pesewas', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descr', sa.String(length=150), nullable=False),
    sa.Column('card', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('usrv', sa.String(length=150), nullable=True),
    sa.Column('fr_om', sa.String(length=150), nullable=True),
    sa.Column('inp_ut', sa.String(length=150), nullable=True),
    sa.Column('curr_balance', sa.String(length=150), nullable=False),
    sa.Column('cedis', sa.String(length=150), nullable=True),
    sa.Column('pesewas', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('image_file', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sent_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descr', sa.String(length=150), nullable=False),
    sa.Column('card', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('requisit', sa.String(length=150), nullable=True),
    sa.Column('t_o', sa.String(length=150), nullable=True),
    sa.Column('out_put', sa.String(length=150), nullable=True),
    sa.Column('avail_balance', sa.String(length=150), nullable=False),
    sa.Column('curr_balance', sa.String(length=150), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_items')
    op.drop_table('user')
    op.drop_table('items')
    op.drop_table('all_trans')
    # ### end Alembic commands ###
